### ISSUE TITLE
build plugin

### ISSUE THREAD

**Issue by Romz24** [AGraber/samp-compat#1]
I don't understand what I'm doing wrong? What do I need to do to correct these errors?
![screenshot00032](https://user-images.githubusercontent.com/2458113/52753492-dd775380-3007-11e9-8731-50a97426f9a7.jpg)

**Comment by AGraber** [comment]
thanks

**Comment by Zorono** [comment]
@Romz24  @AGraber please can you send me the .dll .so(compiled binaries) files  please ???
iamn't experienced on building plugin...
