### ISSUE TITLE
Not working on Linux

### ISSUE THREAD

**Issue by AdrianBZG** [AGraber/samp-compat#5]
Hi,

It looks like this is not working on Linux, I get the following warning when installing:

failed to ensure package github.com/AGraber/samp-compat: failed to ensure asset: failed to get plugin AGraber/samp-compat from net: resource matcher 'samp-compat-linux.zip' does not match any release assets from '[]'

Then I check the plugins folder and there is not .so file in there.

Could I please get an indication on what to do?

Thanks.

**Comment by AdrianBZG** [comment]
@AGraber

**Comment by AGraber** [comment]
Fixed
